### ISSUE TITLE
Issue with token_reset.py 

### ISSUE THREAD

**Issue by Richard-Barrett** [Richard-Barrett/SalesforceCLI#4]
There is a current issue with the token_reset.py script that doesn't account for an MFA prompt to make sure a person is who they are. This script will most likely have to be an interactive prompt and inject the specific page with the credentials that you would normally need to put onto the page.

Current Stack Trace. 
```
Traceback (most recent call last):
  File ".\token_reset.py", line 90, in <module>
    element = WebDriverWait(browser, 20).until(
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

I need to gather all of the specific elements for the MFA Prompt Page and encode that into the script as an interactive prompt with a wait command to give people about thirty seconds to authenticate.

**Comment by Richard-Barrett** [comment]
Not stale, currently working on a way to retrieve a token without having to access Salesforce UI
